# e2e/docker-compose.yml from repo
# https://github.com/bahmutov/cypress-open-from-docker-compose
version: '3.2'
services:
  # this is the web application we are going to test
  sentimentalyzer:
    build: .
    ports:
      - 8123:8000
#    environment:
#      - PORT=8123
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "registry.greenwebplus.com/docker/docker/cypress/included:10.10.0"
    container_name: cypress
    depends_on:
      - sentimentalyzer
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://sentimentalyzer:8123
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - /volumes/cypress:/e2e